# Generated by Django 3.2 on 2021-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('http_method', models.CharField(max_length=255, null=True, verbose_name='Http метод')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='URL')),
                ('answer_code', models.IntegerField(null=True, verbose_name='Код ответа')),
                ('answer_size', models.IntegerField(null=True, verbose_name='Размер ответа')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Записи логов',
            },
        ),
    ]
