# Generated by Django 3.2 on 2021-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateField()),
                ('http_method', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('answer_code', models.IntegerField()),
                ('answer_size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Записи логов',
            },
        ),
    ]
